version: "3.8"

services:
  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: zap
    ports:
      - "8080:8080"
    volumes:
      # [SECURITY FIRST: Жестко связываем абсолютный путь с диска C:]
      # Теперь ZAP будет смотреть ровно туда, куда пишет твой Python
      - C:\zap\wrk:/zap/wrk:rw
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4g
    # Явно прописываем команду запуска сканера в режиме демона
    command: >
      zap.sh -daemon 
      -host 0.0.0.0 
      -port 8080 
      -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true 
      -config api.key=changeme